### ISSUE TITLE
Block exclusion when making pack

### ISSUE THREAD

**Issue by ForestOfLight** [RavinMaddHatter/Structura#42] opened 2021-01-27 19:25 UTC
A space for the user to write blocks they'd like to exclude while the pack creator runs. This makes taking a structure of an underwater (or otherwise embedded, don't ask what-idk) build much easier. Selection from a list may be best so it can just add block names to a temporary banlist. (A couple of grouped things may need to happen, like water including flowing water if/when it's unbanned)

**Comment by RavinMaddHatter** [comment] 2021-01-27 19:34
I would need the Exact block name as in the file. I could make a selection pop up or something. if someone uses a space instead of an _ it would not work as intended. I will think about this a bit more

**Comment by ForestOfGold** [comment] 2021-01-27 19:50
That's what I meant by "selection from a list". It's possible you could just have some preset exclusions to choose from as well- water, lava, stone types, etc. in the end it might even be worth making a similar UI to the nametag one, but that's also pretty quality-of-life b/c I doubt people will use it much.

**Comment by RavinMaddHatter** [comment] 2023-05-23 14:04
Fixed in next update

**Closed by RavinMaddHatter** 2023-05-23 14:04 UTC
Labels: enhancement
